# Generated by Django 5.1.6 on 2025-11-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='features_excluded',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
