# Generated by Django 5.1.6 on 2025-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipplan_features_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='yearly_savings_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
