# Generated by Django 5.1.6 on 2025-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membershippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
