# Generated by Django 5.1.6 on 2025-11-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_changed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
