# Generated by Django 5.1.6 on 2025-10-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category_budgets',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
